@echo off
echo [INFO] Завершаю все python-процессы...
taskkill /F /IM python.exe > nul 2>&1
echo [INFO] Удаляю Webhook...
curl https://api.telegram.org/bot<ТВОЙ_ТОКЕН>/deleteWebhook
echo [INFO] Запускаю бота...
start "" "C:\Users\nikit\AppData\Local\Programs\Python\Python313\python.exe" bot.py
pause
